### ISSUE TITLE
Add config/locales/ja.yml

### ISSUE THREAD

**Issue by KaitoWatanabe** [KaitoWatanabe/rails_template#1]
kaminari

``` yml

ja:
  views:
    pagination:
      first: "&laquo;"
      last: "&raquo;"
      previous: "&lsaquo;"
      next: "&rsaquo;"
      truncate: "..."

```
